### ISSUE TITLE
"Initial download" loop for WGZimmer

### ISSUE THREAD

**Issue by dpusceddu** [Infynyty/Zuap#1]
The Wgzimmer thread suddenly started logging Initial Download every cycle, instead of the usual update of existing insertions.

I have yet to look into it.

**Comment by dpusceddu** [comment]
Using the site, I see a `g-reCAPTCHA-response` parameter in the POST request. I assume that was not there before and it's the reason the bot does not work anymore.

**Comment by Infynyty** [comment]
Thanks for your post. Yes, I just saw that as well. I will look into it a bit more, but I don't think it is reasonable to try to bypass the reCAPTCHA. Maybe they have another API endpoint to use, but I doubt it. I can definitely fix the Initial download bug though.
